"""Hyperparameters and metadata ranges for ReSACO (Table II, Section V-A/V-B)."""

# ----------------------------------------------------------------------------
# Device / Edge / Cloud tier configuration (Section V-A-2, matches
# EdgeCloudSim's scripts/three_tier/config/default_config.properties and
# edge_devices.xml so the trained policy is consistent with the simulator).
# ----------------------------------------------------------------------------
NUM_EDGE_SERVERS = 10
VMS_PER_EDGE_SERVER = 8

MOBILE_VM_MIPS = 4000
MOBILE_VM_CORES = 1

EDGE_VM_MIPS = 10000
EDGE_VM_CORES = 2

CLOUD_VM_COUNT = 4
CLOUD_VM_MIPS = 100000
CLOUD_VM_CORES = 4

WLAN_BANDWIDTH_MBPS = 200
WAN_BANDWIDTH_MBPS = 15
MAN_BANDWIDTH_MBPS = 200
WAN_PROPAGATION_DELAY = 0.1
LAN_INTERNAL_DELAY = 0.005

# Delay threshold used by the network failure indicator F_network (Eq. 2).
TMAX_SECONDS = 5.0

# ----------------------------------------------------------------------------
# Metadata ranges used to build randomized training scenarios (Table II).
# Each entry is a (low, high) range; scenarios are generated by sampling
# uniformly within these bounds.
# ----------------------------------------------------------------------------
METADATA_RANGES = {
    "usage_percentage": (10, 30),
    "poisson_interarrival": (5, 20),
    "delay_sensitivity": (0.0, 1.0),
    "active_period": (10, 60),
    "idle_period": (10, 60),
    "data_upload": (25, 2500),
    "data_download": (25, 2500),
    "task_length": (1500, 10000),
    "vm_utilization_on_edge": (2, 20),
    "vm_utilization_on_cloud": (0.2, 2),
    "vm_utilization_on_mobile": (10, 50),
    "number_of_mobile_devices": (200, 2000),
}
REQUIRED_CORE = 1

# ----------------------------------------------------------------------------
# State / action space (Section IV-A-2)
# state = {L, U, D, mu_d, mu_e1..mu_eN, mu_c, b_wlan, b_man, b_wan}
# action in {0, ..., N+1}: 0 = device, 1..N = edge servers, N+1 = cloud
# ----------------------------------------------------------------------------
STATE_DIM = 4 + NUM_EDGE_SERVERS + 1 + 3  # L,U,D,mu_d + mu_e(N) + mu_c + bwlan,bman,bwan
ACTION_DIM = NUM_EDGE_SERVERS + 2

# ----------------------------------------------------------------------------
# SAC / Reptile hyperparameters (Section V-B-1)
# ----------------------------------------------------------------------------
META_LR = 0.001          # alpha: Reptile meta learning rate
DISCOUNT_GAMMA = 0.99
ENTROPY_TAU = 0.2
REPLAY_BUFFER_SIZE = 100_000
BATCH_SIZE = 64
TARGET_SOFT_UPDATE_RHO = 0.995
CRITIC_LR = 3e-4
ACTOR_LR = 3e-4

NUM_META_SCENARIOS = 10   # M
NUM_OUTER_ITERATIONS = 300  # K
NUM_INNER_SAC_UPDATES = 50  # N

HIDDEN_SIZES = (128, 128)
