all_apps_generic = {
    # General Metrics (ALL)
    0: 'num_of_completed_tasks(ALL)',
    1: 'num_of_failed_tasks(ALL)',
    2: 'num_of_uncompleted_tasks(ALL)',
    3: 'num_of_failed_tasks_due_network(ALL)',
    4: 'average_service_time(ALL)_(sec)',
    5: 'average_processing_time(ALL)_(sec)',
    6: 'average_network_delay(ALL)_(sec)',
    7: 'average_cost',
    8: 'unknown1',
    9: 'num_of_failed_tasks_due_vm_capacity(ALL)',
    10: 'num_of_failed_tasks_due_mobility',
    # Edge Metrics
    11: 'num_of_completed_tasks(Edge)',
    12: 'num_of_failed_tasks(Edge)',
    13: 'num_of_uncompleted_tasks(Edge)',
    14: 'unknown2',
    15: 'average_service_time(Edge)_(sec)',
    16: 'average_processing_time(Edge)_(sec)',
    17: 'unknown3',
    18: 'average_server_utilization(Edge)_(%)',
    19: 'num_of_failed_tasks_due_vm_capacity(Edge)',
    # Cloud Metrics
    20: 'num_of_completed_tasks(Cloud)',
    21: 'num_of_failed_tasks(Cloud)',
    22: 'num_of_uncompleted_tasks(Cloud)',
    23: 'num_of_failed_tasks_due_vm_capacity(Cloud)',
    24: 'average_service_time(Cloud)_(sec)',
    25: 'average_processing_time(Cloud)_(sec)',
    26: 'unknown4',
    27: 'average_server_utilization(Cloud)_(%)',
    28: 'num_of_failed_tasks_due_vm_capacity(Cloud)',
    # Mobile Metrics
    29: 'num_of_completed_tasks(Mobile)',
    30: 'num_of_failed_tasks(Mobile)',
    31: 'num_of_uncompleted_tasks(Mobile)',
    32: 'unknown5',
    33: 'average_service_time(Mobile)_(sec)',
    34: 'average_processing_time(Mobile)_(sec)',
    35: 'unknown6',
    36: 'average_server_utilization(Mobile)_(%)',
    37: 'num_of_failed_tasks_due_vm_capacity(Mobile)',
    # Network Delay Metrics
    38: 'average_LAN_delay_(sec)',
    39: 'average_MAN_delay_(sec)',
    40: 'average_WAN_delay_(sec)',
    # Network Failure Metrics
    41: 'unknown7',
    42: 'num_of_failed_tasks_due_network(WLAN)',
    43: 'num_of_failed_tasks_due_network(MAN)',
    44: 'num_of_failed_tasks_due_network(WAN)',
}
